# Generated by Django 4.1.5 on 2023-01-13 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('class_id', models.IntegerField(default=0)),
                ('class_name', models.CharField(default='Warrior', max_length=100)),
                ('spec', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vault of Incarnates', max_length=100)),
                ('start_date', models.CharField(default='1.1.2023', max_length=20)),
                ('end_date', models.CharField(default='1.1.2023', max_length=20)),
                ('start_time', models.CharField(default='21:00', max_length=100)),
                ('end_time', models.CharField(default='24:00', max_length=100)),
                ('deadline', models.CharField(default='16:30', max_length=100)),
                ('description', models.CharField(blank=True, default='Пред инстанцията в 20:45', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowcalendar.class')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='tempEmail@domain.com', max_length=254)),
                ('profile_username', models.CharField(default='temp_username', max_length=50)),
                ('role', models.CharField(blank=True, default='User', max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowcalendar.character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowcalendar.event')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowcalendar.profile')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wowcalendar.profile'),
        ),
    ]
