# Generated by Django 4.1.5 on 2023-01-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status_set',
            field=models.IntegerField(default=0),
        ),
    ]
