# Generated by Django 4.1.5 on 2023-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event', max_length=100)),
                ('start_date', models.CharField(default='1.1.2023', max_length=20)),
                ('end_date', models.CharField(default='1.1.2023', max_length=20)),
                ('start_time', models.CharField(default='21:00', max_length=100)),
                ('end_time', models.CharField(default='24:00', max_length=100)),
                ('deadline', models.CharField(default='16:30', max_length=100)),
                ('description', models.CharField(blank=True, default='Пред инстанцията в 20:45', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
