# Generated by Django 4.1.5 on 2023-01-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowcalendar', '0002_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='start_date',
        ),
    ]
